// Audit trail: every AI action is reproducible from its commit body.
// Git is the audit log (PLAN.md §7).
import type { RiskClass } from "./policy.js";
import type { RunResult } from "./claude.js";

export interface AuditRecord {
  prompt: string;
  target: string;
  result: RunResult;
  cls: RiskClass;
}

/** Build a conventional-commit body that captures the full provenance of an AI change. */
export function commitMessage(rec: AuditRecord): string {
  const { result, prompt, target, cls } = rec;
  const u = result.usage;
  return [
    `chore(ai): apply /${prompt} to ${target}`,
    "",
    `AI-Prompt: ${prompt}`,
    `AI-Model: ${result.model}`,
    `AI-Target: ${target}`,
    `AI-Class: ${cls}`,
    `AI-Tokens: in=${u.inputTokens} out=${u.outputTokens} cache_read=${u.cacheReadTokens} cache_create=${u.cacheCreationTokens}`,
    "",
    "Generated by the BASH OS AI engine. Provenance recorded for audit.",
  ].join("\n");
}

/** One-line summary for stdout / CI logs. */
export function summarize(rec: AuditRecord): string {
  const u = rec.result.usage;
  return `[${rec.cls}] /${rec.prompt} → ${rec.target} (${rec.result.model}; ${u.inputTokens}+${u.outputTokens} tok, ${u.cacheReadTokens} cached)`;
}
