#!/usr/bin/env python3
"""Generate _includes/brand/mark-shape.svg from the canonical BASH mark.

The interactive hero (assets/js/constellation.js) needs the B mark's outline as
plain SVG path data it can hit-test against. Rather than hand-copying that
geometry into an include — where it would drift the next time the mark is
re-exported — this script pulls it straight from the file of record,
assets/brand/favicon.svg, and writes a minimal, label-free SVG include.

Reads (by Inkscape label, which is how the mark's layers are named):
  layer  "B-Logo"   -> its translate() transform
  path   "outer-B"  -> the filled B                       (data-shape="fill")
  path   "inner-c"  -> the white counter drawn over it    (data-shape="hole")

Design constraints:
  - Standard library only. The SVG is parsed with xml.etree; no rasterizer
    and no path maths — the browser samples the geometry at runtime.
  - Deterministic: same input bytes -> same output bytes, no timestamps.
  - The rendered `d` (with Inkscape's fillet effect applied) is used, never
    `inkscape:original-d`, so the include matches what the favicon shows.

Usage:
  python3 scripts/generate_mark_shape.py          # writes _includes/brand/mark-shape.svg
  python3 scripts/generate_mark_shape.py --check  # exit 1 if the include is stale
"""

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "assets" / "brand" / "favicon.svg"
OUTPUT = REPO_ROOT / "_includes" / "brand" / "mark-shape.svg"

SVG_NS = "http://www.w3.org/2000/svg"
INKSCAPE_NS = "http://www.inkscape.org/namespaces/inkscape"
LABEL = f"{{{INKSCAPE_NS}}}label"

LAYER_LABEL = "B-Logo"
PATHS = (("outer-B", "fill"), ("inner-c", "hole"))


def find_labelled(root: ET.Element, tag: str, label: str) -> ET.Element:
    for el in root.iter(f"{{{SVG_NS}}}{tag}"):
        if el.get(LABEL) == label:
            return el
    raise SystemExit(f"{SOURCE.relative_to(REPO_ROOT)}: no <{tag}> labelled {label!r}")


def render() -> str:
    root = ET.parse(SOURCE).getroot()
    view_box = root.get("viewBox")
    if not view_box:
        raise SystemExit(f"{SOURCE.relative_to(REPO_ROOT)}: missing viewBox")

    layer = find_labelled(root, "g", LAYER_LABEL)
    transform = layer.get("transform", "")

    rel = SOURCE.relative_to(REPO_ROOT).as_posix()
    me = Path(__file__).resolve().relative_to(REPO_ROOT).as_posix()
    lines = [
        "{%- comment -%}",
        f"  GENERATED by {me} from {rel} — do not edit by hand.",
        "  Geometry source for the interactive mark (assets/js/constellation.js, svg",
        "  source): stars are sampled inside the fill and outside the hole, densest",
        "  along the outline. Re-run the generator after re-exporting the favicon.",
        "{%- endcomment -%}",
        f'<svg viewBox="{view_box}" aria-hidden="true" focusable="false" data-constellation-shape>',
        f'  <g transform="{transform}">' if transform else "  <g>",
    ]
    for label, role in PATHS:
        path = find_labelled(layer, "path", label)
        d = " ".join(path.get("d", "").split())
        if not d:
            raise SystemExit(f"{rel}: path {label!r} has no d attribute")
        lines.append(f'    <path data-shape="{role}" d="{d}"/>')
    lines += ["  </g>", "</svg>", ""]
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv[1:]
    content = render()
    rel_out = OUTPUT.relative_to(REPO_ROOT)
    if check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != content:
            print(f"{rel_out} is stale — run: python3 scripts/generate_mark_shape.py")
            return 1
        print(f"{rel_out} is up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {rel_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
